apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: otus
  labels:
    app: notification
spec:
  selector:
    app: notification
  ports:
    - name: web
      protocol: TCP
      port: 8000
      targetPort: http
  type: NodePort