version: '3.3'

services:
  user-dev:
    image: echernukha/user
    container_name: user-dev
    build:
      context: .
      dockerfile: User.Dockerfile
    ports:
      - "8000:8000" # REST API port
    environment:
      USER_DB_HOST: user-db-dev:3306
      USER_DB_NAME: user
      USER_DB_USER: user
      USER_DB_PASSWORD: gBe-o9dNFF
      # Coupled with MySQL 'max_connections' option: must be 'max_connections - 5'
      USER_DB_MAX_CONN: 5
    depends_on:
      - user-db-dev

  user-db-dev:
    image: percona
    container_name: user-db-dev
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: user
      MYSQL_USER: user
      MYSQL_PASSWORD: gBe-o9dNFF
    volumes:
      - "user-db-dev-data:/var/lib/mysql"
      - "${PWD}/data/mysql/config/:/etc/my.cnf.d"

volumes:
  user-db-dev-data:
