apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: otus
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: echernukha/auth:latest
          name: authcontainer
          env:
            - name: AUTH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: AUTH_JWT_SECRET
            - name: AUTH_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: AUTH_DB_HOST
            - name: AUTH_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: AUTH_DB_NAME
            - name: AUTH_DB_USER
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: AUTH_DB_USER
            - name: AUTH_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: AUTH_DB_PASSWORD
            - name: AUTH_AMQP_HOST
              value: "rabbitmq"
            - name: AUTH_AMQP_PORT
              value: "5552"
            - name: AUTH_AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: AUTH_AMQP_USER
            - name: AUTH_AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: AUTH_AMQP_PASSWORD
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 10