apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: billing
  labels:
    app: billing
spec:
  namespaceSelector:
    matchNames:
      - otus
  selector:
    matchLabels:
      app: billing
  endpoints:
    - interval: 15s
      port: web
      path: /monitoring