apiVersion: v1
kind: Service
metadata:
  name: stock
  namespace: otus
  labels:
    app: stock
spec:
  selector:
    app: stock
  ports:
    - name: web
      protocol: TCP
      port: 8000
      targetPort: http
  type: NodePort