apiVersion: v1
kind: Service
metadata:
  name: delivery
  namespace: otus
  labels:
    app: delivery
spec:
  selector:
    app: delivery
  ports:
    - name: web
      protocol: TCP
      port: 8000
      targetPort: http
  type: NodePort