apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notification
  labels:
    app: notification
spec:
  namespaceSelector:
    matchNames:
      - otus
  selector:
    matchLabels:
      app: notification
  endpoints:
    - interval: 15s
      port: web
      path: /monitoring