apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: otus
  labels:
    app: user
spec:
  selector:
    matchLabels:
      app: user
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - image: echernukha/user:latest
          name: usercontainer
          env:
            - name: USER_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: USER_JWT_SECRET
            - name: USER_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: USER_DB_HOST
            - name: USER_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: USER_DB_NAME
            - name: USER_DB_USER
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: USER_DB_USER
            - name: USER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: USER_DB_PASSWORD
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: otus
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: echernukha/auth:latest
          name: authcontainer
          env:
            - name: AUTH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: AUTH_JWT_SECRET
            - name: AUTH_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: AUTH_DB_HOST
            - name: AUTH_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: AUTH_DB_NAME
            - name: AUTH_DB_USER
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: AUTH_DB_USER
            - name: AUTH_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: AUTH_DB_PASSWORD
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5