apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
  namespace: otus
  labels:
    app: store
spec:
  selector:
    matchLabels:
      app: store
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
        - image: echernukha/store:latest
          name: storecontainer
          env:
            - name: STORE_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: store-secret
                  key: STORE_DB_HOST
            - name: STORE_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: store-secret
                  key: STORE_DB_NAME
            - name: STORE_DB_USER
              valueFrom:
                secretKeyRef:
                  name: store-secret
                  key: STORE_DB_USER
            - name: STORE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: store-secret
                  key: STORE_DB_PASSWORD
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5