apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store
  namespace: otus
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: arch.homework
    http:
      paths:
      - backend:
          service:
            name: store
            port:
              number: 8000
        pathType: Prefix
        path: /