apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user
  labels:
    app: user
spec:
  namespaceSelector:
    matchNames:
      - otus
  selector:
    matchLabels:
      app: user
  endpoints:
    - interval: 15s
      port: web
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth
  labels:
    app: auth
spec:
  namespaceSelector:
    matchNames:
      - otus
  selector:
    matchLabels:
      app: auth
  endpoints:
    - interval: 15s
      port: web
      path: /metrics