apiVersion: v1
kind: Service
metadata:
  name: store
  namespace: otus
  labels:
    app: store
spec:
  selector:
    app: store
  ports:
  - name: web
    protocol: TCP
    port: 8000
    targetPort: http
  type: NodePort