apiVersion: v1
kind: Service
metadata:
  name: billing
  namespace: otus
  labels:
    app: billing
spec:
  selector:
    app: billing
  ports:
    - name: web
      protocol: TCP
      port: 8000
      targetPort: http
  type: NodePort