{
 "title": "store-dashboard",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,5m,10m,30m,1h,6h,12h,1d"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pg_release",
    "label": "Postgres Release",
    "query": {
     "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
    }
   },
   {
    "name": "pg_instance",
    "label": "Postgres Instance",
    "query": {
     "query": "query_result(pg_up{release=\"$pg_release\"})"
    }
   },
   { "name": "pg_datname", "label": "Postgres Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "pg_mode",
    "label": "Postgres Lock table",
    "query": {
     "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
    }
   }
  ]
 },
 "panels": [
  { "title": "user", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(app_request_latency_seconds_count{service=\"user\", namespace=\"$namespace\"}[$interval])) by (exported_endpoint, method)",
     "legendFormat": "{{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by (status)(increase(app_request_latency_seconds_count{status=~\"5.+\"}[$interval]))",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum by (status)(increase(app_request_latency_seconds_count{status=~\"4.+\"}[$interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(app_request_latency_seconds_bucket{service=\"user\", namespace=\"$namespace\", exported_endpoint=~\"/api/v1.*\"}[$interval])) by (le))*1000",
     "legendFormat": "0.5 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_request_latency_seconds_bucket{service=\"user\", namespace=\"$namespace\", exported_endpoint=~\"/api/v1.*\"}[$interval])) by (le))*1000",
     "legendFormat": "0.95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_request_latency_seconds_bucket{service=\"user\", namespace=\"$namespace\", exported_endpoint=~\"/api/v1.*\"}[$interval])) by (le))*1000",
     "legendFormat": "0.99 quantile"
    }
   ]
  },
  {
   "title": "Latency by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(app_request_latency_seconds_bucket{service=\"user\", namespace=\"$namespace\", exported_endpoint=~\"/api/v1.*\"}[$interval])) by (exported_endpoint, method, le))*1000",
     "legendFormat": "q 0.5 {{method}} {{exported_endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_request_latency_seconds_bucket{service=\"user\", namespace=\"$namespace\", exported_endpoint=~\"/api/v1.*\"}[$interval])) by (exported_endpoint, method, le))*1000",
     "legendFormat": "q 0.95 {{method}} {{exported_endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(app_request_latency_seconds_bucket{service=\"user\", namespace=\"$namespace\", exported_endpoint=~\"/api/v1.*\"}[$interval])) by (exported_endpoint, method, le))*1000",
     "legendFormat": "q 0.99 {{method}} {{exported_endpoint}}"
    }
   ]
  },
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Nginx Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"user\"}[2m])) by (le))*1000",
     "legendFormat": "0.5 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"user\"}[2m])) by (le))*1000",
     "legendFormat": "0.95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"user\"}[2m])) by (le))*1000",
     "legendFormat": "0.99 quantile"
    }
   ]
  },
  {
   "title": "Nginx RPS by status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{exported_service=\"user\", exported_namespace=\"$namespace\"}[$interval])) by (status)",
     "legendFormat": "status - {{status}}"
    }
   ]
  },
  {
   "title": "Nginx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum by (status)(increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[2m]))",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum by (status)(increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"4.+\"}[2m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "user Pod Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=\"usercontainer\"}) by (pod)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"usercontainer\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}