apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: otus
  labels:
    app: order
spec:
  selector:
    matchLabels:
      app: order
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - image: echernukha/order:latest
          name: ordercontainer
          env:
            - name: ORDER_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: ORDER_JWT_SECRET
            - name: ORDER_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: ORDER_DB_HOST
            - name: ORDER_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: ORDER_DB_NAME
            - name: ORDER_DB_USER
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: ORDER_DB_USER
            - name: ORDER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: ORDER_DB_PASSWORD
            - name: ORDER_AMQP_HOST
              value: "rabbitmq"
            - name: ORDER_AMQP_PORT
              value: "5552"
            - name: ORDER_AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: ORDER_AMQP_USER
            - name: ORDER_AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: ORDER_AMQP_PASSWORD
            - name: ORDER_BILLING_HOST
              value: "http://billing:8000"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 10