apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: otus
  labels:
    app: order
spec:
  selector:
    app: order
  ports:
    - name: web
      protocol: TCP
      port: 8000
      targetPort: http
  type: NodePort