apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stock
  labels:
    app: stock
spec:
  namespaceSelector:
    matchNames:
      - otus
  selector:
    matchLabels:
      app: stock
  endpoints:
    - interval: 15s
      port: web
      path: /monitoring